# Generated by Django 5.1.3 on 2024-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='profile_img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='images_crowfunding/'),
        ),
    ]
