# Generated by Django 5.1.3 on 2024-11-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='profile_img',
            field=models.ImageField(blank=True, default='images_crowfunding/fallback.png', upload_to='images_crowfunding/'),
        ),
    ]
